FROM ruby

RUN gem i osc-repl osc-ruby-ng --source http://gems.neurogami.com

EXPOSE 5005/udp

WORKDIR /ornette

CMD ['osc-repl']
ENTRYPOINT 'server.yaml'


# apt install -y ruby && gem i osc-repl osc-ruby-ng --source http://gems.neurogami.com && osc-repl server.yaml