# Ornette base image
FROM python:3.8-slim-buster

# Build Ornette Deps
RUN pip3 install --upgrade pip
RUN pip3 install python-osc pretty_errors mido

RUN mkdir /ornette
WORKDIR /ornette
EXPOSE 5005/udp